### ISSUE TITLE
Problem running the pretrained model: PytorchStreamReader failed reading zip archive

### ISSUE THREAD

**Issue by kamzero** [cangumeli/ObjectMatch#1]
Hi, 
I downloaded the pretrained model from the following link as mentioned in the README.md file:
https://tumde-my.sharepoint.com/personal/can_guemeli_tum_de/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fcan%5Fguemeli%5Ftum%5Fde%2FDocuments%2FObjectMatch&ga=1

However, when I tried to run the script using the following command:
```
python pair_eval.py --file ./assets/samples.txt --test_folder ./assets/sample_pairs --vis
```
I encountered the following problem:

```
PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted
  File "/mnt/nas/share/home/jxr/home/code/ObjectMatch/nocpred/engine/predictor.py", line 22, in __init__
    self.model.load_state_dict(torch.load(model_path)['model'], strict=False)
  File "/mnt/nas/share/home/jxr/home/code/ObjectMatch/pairwise_backend.py", line 151, in _build_networks
    self.noc_pred = NOCPredictor(self.nocpred_cfg.d2_cfg, self.nocpred_cfg.model_file)
  File "/mnt/nas/share/home/jxr/home/code/ObjectMatch/pairwise_backend.py", line 147, in __init__
    self._build_networks()
  File "/mnt/nas/share/home/jxr/home/code/ObjectMatch/pair_eval.py", line 45, in main
    solver = PairwiseSolver(
  File "/mnt/nas/share/home/jxr/home/code/ObjectMatch/pair_eval.py", line 138, in <module>
    main(sys.argv[1:])
RuntimeError: PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted
```

It seems like there is something wrong with the model checkpoint `checkpoints/model_sym.pth`. I suspect it might be corrupted or there is an issue with the file. Could you please check this for me?

Thank you!

**Comment by cangumeli** [comment]
Thanks a lot for the issue!

I re-uploaded the checkpoints folder to the same drive w/o zipping. The new archive seems to work on my computer, can you try that out?

**Comment by kamzero** [comment]
It works well now. Thanks :D
