### ISSUE TITLE
Pre-trained network weights link expired

### ISSUE THREAD

**Issue by UsamaHasan** [cangumeli/ObjectMatch#2]
Hy there, thank you for making this code public. I have tried accessing the link that you have provided for pre-trained network weights, but it's expired. Can you please refresh it.
![Uploading Screenshot from 2023-09-08 16-06-04.png…]()

**Comment by UsamaHasan** [comment]
@cangumeli Any chance that you can respond to this.

**Comment by cangumeli** [comment]
Hi, thanks for your interest, and sorry for the late response. I updated the link in the README to Google Drive, could you check whether that works? The new link is this: https://drive.google.com/drive/folders/1ATd3A7_ry4_6NbRDLfywKvtntsZS_UZE?usp=drive_link

**Comment by UsamaHasan** [comment]
Thank you so much @cangumeli. The link works perfectly.
